### PR TITLE
added functionality to show ongoing multi-day events

### LINKED ISSUE #114: Add ability to display ongoing multiday events
Currently, the plugin only shows events that start on the specified date. If there are multiday events ongoing (start date *before* and end date *after* the daily note), these are not displayed on subsequent days. Is it possible/feasible to add this functionality? Whether it be as default, or optional behaviour.

### PR DESCRIPTION
**Pull request by The1029**
Closed #114. I have set this to be "off" by default to prevent a change in behaviour for existing users, but please feel free to modify.

### CODE REVIEW

**Comment by Cateroo** [comment]
Thanks for this! Is there something we need to do to the plugin to turn on this functionality?

**Comment by The1029** [comment]
No problem, @Cateroo! To enable, go into the settings page, edit the calendar, and there is now a new preference at the bottom called 'Show Ongoing'. It is set to off by default, but once switched on for each calendar the setting should be saved.

**Comment by Cateroo** [comment]
Thanks - I just checked the settings and the "show ongoing" option was already on by default in all my calendars, but they're not showing up in the daily task lists 😅

It currently shows the version as 1.6.5, so that seems right.

**Comment by The1029** [comment]
Hi Cateroo. Can you try toggling the setting off then on again for all calendars? It may be that the new preference is “undefined” to start with in existing installs.

**Comment by Cateroo** [comment]
yep - that sorted it out, thanks so much!!

**Pull request merged**
